---
abstract: "Run external commands at specific phases of Dist::Zilla on regex'd Git branches"
author:
  - 'Matt Finkel <finkel.matt@gmail.com> L<http://mfinkel.net/>'
build_requires:
  Dist::Zilla::Tester: 0
  Path::Class: 0
  Test::Git: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-RunByBranch
requires:
  Dist::Zilla::Plugin::Run::AfterBuild: 0
  Dist::Zilla::Plugin::Run::AfterMint: 0
  Dist::Zilla::Plugin::Run::AfterRelease: 0
  Dist::Zilla::Plugin::Run::BeforeBuild: 0
  Dist::Zilla::Plugin::Run::BeforeRelease: 0
  Dist::Zilla::Plugin::Run::Release: 0
  Dist::Zilla::Plugin::Run::Test: 0
  Dist::Zilla::Role::Git::Repo: 0
  Moose: 0
  Moose::Role: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
version: 0.213
x_authority: cpan:FFFINKEL
